@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.loot.crafting.ingredient;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;