@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.treasurebags.lib;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;