@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.treasurebags.crafting.recipe;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;