@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.treasurebags.crafting.ingredient;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;