@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.treasurebags.setup;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;