@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.treasurebags.setup;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;