@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.loot.crafting.recipe;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;